[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = ["cd /app && npm ci --workspace=client --include-workspace-root"]

[phases.build]
cmds = ["cd /app/client && npm run build"]

[start]
cmd = "npx serve /app/client/dist -s -l 8080"
