[phases.setup]
nixPkgs = [
  "python311Full",
  "python311Packages.pip",
  "gcc",
  "libGL",
  "glib",
  "xorg.libxcb",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libXau",
  "xorg.libXdmcp",
]
aptPkgs = [
  "libgl1",
  "libglib2.0-0",
  "libxcb1",
  "libx11-6",
  "libxext6",
  "libxrender1",
  "libxau6",
  "libxdmcp6",
  "libsm6",
  "libice6",
  "libxfixes3",
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements-prod.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python -m uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"
